name: Build + test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run unit tests
        shell: bash
        run: scripts/tests.unit.sh
